name: Web Login

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */5 * * *'

jobs:
  run_puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Playwright
        run: python -m pip install playwright

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Pyppeteer
        run: python -m pip install pyppeteer

      - name: Run Puppeteer Python script
        run: python login.py
