name: Web Login

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */5 * * *'

jobs:
  run_puppeteer:
    runs-on: ubuntu-latest
    container:
      image: buildkite/agent
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyppeteer pyppeteer_stealth
      
      - name: Run Python script
        run: |
          python login.py
