name: Web Login

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */5 * * *'

jobs:
  run_puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyppeteer pyppeteer_stealth
      
      - name: Run Python script
        run: |
          python login.py
